---
- block:
    - name: Create default LXD storage
      shell: "{{ lxd_bin_folder }}/lxc storage create default dir source=/var/snap/lxd/common/lxd/storage-pools"
      register: default_storage_add
      changed_when: "default_storage_add.rc == 0"
      failed_when:
        - "default_storage_add.rc != 0"
        - "'already exists' not in default_storage_add.stderr"

    - name: Create LXD networks
      lxd_network:
        name: "{{ item.name }}"
        state: "present"
        config: "{{ item.config }}"
        description: "{{ item.description }}"
        url: "{{ lxd_url }}"
      with_items: "{{ lxd_networks }}"
      when: "lxd_networks is defined"
  tags: lxd_config
