---
- name: Create containers
  lxd_container:
    name: "{{ item.name }}"
    state: started
    source:
      type: image
      mode: pull
      server: https://images.linuxcontainers.org
      protocol: simplestreams
      alias: "{{ item.alias }}"
    profiles: "{{ item.profiles | default({}) }}"
    devices: "{{ item.devices | default({}) }}"
    wait_for_ipv4_addresses: true
  with_items: "{{ lxd_containers }}"
  when: "lxd_containers is defined"

- name: Add containers to dynamic inventory
  add_host:
    name: "{{ item.name }}"
    ansible_connection: lxd
  with_items: "{{ lxd_containers }}"
  changed_when: false
  loop_control:
    label: "{{ item.name }}"

- name: Installing python and updating containers
  raw: "/bin/bash -c '[[ -f /etc/debian_version && ! -f /usr/bin/python ]] && apt-get -y update && apt-get -y install python ca-certificates || true'"
  with_items: "{{ lxd_containers }}"
  delegate_to: "{{ item.name }}" 
  changed_when: false
  become: false
