---
- name: Création des containers
  lxd_container:
    name: "{{ item.name }}"
    state: started
    source:
      type: image
      mode: pull
      server: https://images.linuxcontainers.org
      protocol: simplestreams
      alias: "{{ item.alias }}"
    profiles: "{{ item.profiles | default({}) }}"
    devices: "{{ item.devices | default({}) }}"
    wait_for_ipv4_addresses: true
  with_items: "{{ lxd_containers }}"
  when: "lxd_containers is defined"

- name: Ajout des containers créés à l'inventaire dynamique
  add_host:
    name: "{{ item.name }}"
    ansible_connection: lxd
  with_items: "{{ lxd_containers }}"
  changed_when: false
  loop_control:
    label: "{{ item.name }}"

- name: Installation de python sur les containers
  raw: |
    test -e /etc/redhat-release && manager='yum'
    test -e /etc/debian_version && manager='apt-get' && extra='ca-certificates'
    $manager -y install python $extra
  with_items: "{{ lxd_containers }}"
  delegate_to: "{{ item.name }}" 
  changed_when: false
  become: false
  loop_control:
    label: "{{ item.name }}"
