---
- name: Création des containers
  lxd_container:
    name: "{{ item.name }}"
    state: started
    source:
      type: image
      mode: pull
      server: https://images.linuxcontainers.org
      protocol: simplestreams
      alias: "{{ item.alias }}"
    profiles: "{{ item.profiles | default({}) }}"
    devices: "{{ item.devices | default({}) }}"
    wait_for_ipv4_addresses: true
  with_items: "{{ lxd_containers }}"
  when: "lxd_containers is defined"
  register: add_lxd_container

- name: Ajout des containers créés à l'inventaire dynamique
  add_host:
    name: "{{ item.item.name }}"
    ansible_connection: lxd
  with_items: "{{ add_lxd_container.results }}"
  when: "'create' in item.actions"
  changed_when: None
  loop_control:
    label: "{{ item.item.name }}"

- name: Installation de python sur les containers CentOS
  raw: yum -y install python
  delegate_to: "{{ item.item.name }}"
  with_items: "{{ add_lxd_container.results }}"
  when:
    - "'create' in item.actions"
    - "'centos' in item.item.alias"
  become: false

- name: Installation de python sur les containers Debian
  raw: apt-get update && apt-get -y install python ca-certificates
  delegate_to: "{{ item.item.name }}"
  with_items: "{{ add_lxd_container.results }}"
  when:
    - "'create' in item.actions"
    - "'ubuntu' in item.item.alias or 'debian' in item.item.alias"
  become: false

- name: Installation de gpg pour Debian 9 et le module apt_key
  raw: apt-get -y install gpg
  delegate_to: "{{ item.item.name }}"
  with_items: "{{ add_lxd_container.results }}"
  when:
    - "'create' in item.actions"
    - "'stretch' in item.item.alias"
  become: false
