---
- name: start lxd
  service:
    name: "{{ lxd_service_name }}"
    state: started
    enabled: yes

- name: restart lxd
  service:
    name: "{{ lxd_service_name }}"
    state: restarted

- name: wait for socket
  wait_for:
    path: "{{ lxd_socket_path }}"
    timeout: 60
...
